{{- if .Values.secret.create -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (include "app-ruan.fullname" .) }}
  labels:
    {{- include "app-ruan.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc }}
{{- end -}}

{{- end -}}

